apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job-v1
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
      - name: hello-world-v1
        image: busybox
        command: ['sh', '-c', 'echo "bad idea!"; ps aux; sleep 30']
      restartPolicy: Never
