apiVersion: batch/v1
kind: pod
metadata:
  name: hello-world-service
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
        command: ['sh', '-c', 'echo "Good Word!! hello world"; sleep 20']
      restartPolicy: Never
