apiVersion: v1
kind: Pod
metadata:
  name: hello-world-service
spec:
  containers:
  - name: hello-world
    image: busybox
    command: ['sh', '-c', 'echo "Good Word!! hello world"; sleep 20']
    restartPolicy: Never
