apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
        command: ['sh', '-c', 'echo "Bad world!!!"; sleep 60']
      restartPolicy: Never
